# Generated by Django 3.2.7 on 2021-11-28 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playername',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teamname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playerscores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attackdecisionrate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=2, null=True, verbose_name='')),
                ('returnrate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=2, null=True, verbose_name='')),
                ('spike_success', models.PositiveIntegerField()),
                ('spike_not_success', models.PositiveIntegerField()),
                ('receive_success', models.PositiveIntegerField()),
                ('receive_not_success', models.PositiveIntegerField()),
                ('block_success', models.PositiveIntegerField()),
                ('serve_not_effect', models.PositiveIntegerField()),
                ('Notouch_ace', models.PositiveIntegerField()),
                ('ace', models.PositiveIntegerField()),
                ('effect', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volleyapp.playername')),
            ],
        ),
        migrations.AddField(
            model_name='playername',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volleyapp.teamname'),
        ),
    ]
