# Generated by Django 3.2.7 on 2021-11-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volleyapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerscores',
            name='attackdecisionrate',
        ),
        migrations.RemoveField(
            model_name='playerscores',
            name='returnrate',
        ),
    ]
