# Generated by Django 3.2.7 on 2021-11-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volleyapp', '0002_auto_20211128_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerscores',
            name='opponent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
